### ISSUE TITLE
Date-picker autohide not working on mobile

### ISSUE THREAD

**Issue by xlegs** [fulup-bzh/DatePicker#15]
This is caused by the dependency on 'mousedown' (lines 627 and 663). Replacing 'mousedown' with 'touchstart' resolves the issue on mobile, but cause the same issue to occur on the desktop.

Can we make it work on both platforms? I tried adding JQueryMobile's vmouse library, but I couldn't get it to work.

For reference: https://api.jquerymobile.com/vmousedown/ and https://stackoverflow.com/questions/11144370/using-mousedown-event-on-mobile-without-jquery-mobile

**Comment by fulup-bzh** [comment]
Please propose a patch

**Comment by xlegs** [comment]
I would love to, but I'm not a seasoned angular dev. I'm trying to use Modernizer's touchevents, but I keep running into errors.
