### ISSUE TITLE
Clicking the Header date or Header arrows closes the datepicker

### ISSUE THREAD

**Issue by CaryLandholt** [fulup-bzh/DatePicker#3]
This happens on the demo site.
http://breizhme.net/datepicker/demo/index.html

**Comment by fulup-bzh** [comment]
Hoops, I introduce a bug. Thank you for the information, I will dig further

**Comment by fulup-bzh** [comment]
It should be fixed now both for git and for the demo.

**Comment by CaryLandholt** [comment]
Thanks!  Have you uploaded the changes to the demo site?
It's not working there.

**Comment by CaryLandholt** [comment]
Ahh.  Nevermind.  Just performed a hard refresh.  All is good.

Thanks for the quick response.

**Comment by fulup-bzh** [comment]
The demo work for me, it should work for you. Did you flush your cache with a SHIFT+F5 ?
