### ISSUE TITLE
Datepicker do not close while clicking outside

### ISSUE THREAD

**Issue by bodhisatwag** [fulup-bzh/DatePicker#4]
The Foundation/Bootstrap/jQuery datepickers close on clicking outside it. But this one does not. Please look into it. Might be a simple blody click event would work.

**Comment by fulup-bzh** [comment]
You're right, this is a new bug coming from my last correction. I unfortunately doubt to have time to fix it before next week. In the mean time "esc" close the picker.

**Comment by fulup-bzh** [comment]
I need to dig more, I tried a quick fix by adding inside "scope.bindevent" method a  window.addEventListener("click", closepicker , true). Unfortunately this listener trap mouse click both inside and outside the picker. 

If you have any idea of a good model to trap mouseclick when outside the picker, please let me know.
